- cmd/admin/handlers-get.go
- cmd/admin/handlers-post.go
- cmd/admin/json-carves.go
- cmd/admin/json-queries.go
- cmd/admin/static/css/custom.css
- cmd/admin/templates/carves-details.html
- cmd/admin/templates/carves-run.html
- cmd/admin/templates/carves.html
- cmd/admin/templates/components/page-aside-left.html
- cmd/admin/templates/components/page-aside-right.html
- cmd/admin/templates/components/page-header.html
- cmd/admin/templates/conf.html
- cmd/admin/templates/enroll.html
- cmd/admin/templates/environments.html
- cmd/admin/templates/node.html
- cmd/admin/templates/queries-logs.html
- cmd/admin/templates/queries-run.html
- cmd/admin/templates/queries.html
- cmd/admin/templates/settings.html
- cmd/admin/templates/table.html
- cmd/admin/templates/users.html
- cmd/admin/types-templates.go
- cmd/admin/utils.go
- pkg/types/types.go
* Show service name and service version in the subsection where settings are accessed.
* Better handling of templates metadata, and the refactoring of that.
> Show service version in admin UI

- tools/git-release.sh
- tools/vagrant_tmux.sh
* Adding tool to cut a release using the API, so it will show in `latest` releases.
> Adding tools

- admin/handlers-post.go
- admin/templates/settings.html
- admin/templates/table.html
- admin/templates/users.html
Closing #18, making users editable for Email and Fullname.
> Users are editable

- admin/templates/carves.html
- admin/templates/queries.html
- admin/templates/table.html
Fixed bug #29 when all elements on a table would get actioned ignoring the filter applied.
> Fixed bug with select

- admin/json-nodes.go
- admin/json-stats.go
- admin/templates/components/page-aside-left.html
Nodes can be displayed by environment or by platform. But by platform will only be displayed to admins.
> Platform view only for admins

- logging/db.go
- nodes/nodes.go
Fix for #82 where UUIDs were not found due to inconsistent casing
> Fix for UUIDs bug

- utils/http-utils.go
Fix for #94 
Avoid using `InsecureSkipVerify` when sending requests to `HTTPS`
> Verify properly HTTPS requests

- README.md
Donation wallets in `README` for BTC and ETH donations. Thanks in advance! ❤️
> Adding BTC and ETH wallets for donations

- admin/handlers/get.go
- admin/handlers/go.sum
- admin/handlers/json-nodes.go
- admin/handlers/json-queries.go
- admin/handlers/json-stats.go
- admin/handlers/post.go
- admin/handlers/templates.go
- admin/handlers/utils.go
- admin/main.go
- admin/static/js/stats.js
- admin/templates/components/page-aside-left.html
- cli/environment.go
- environments/environments.go
- environments/go.mod
- environments/go.sum
- environments/util.go
- go.sum
Fix for #93 with some linter warnings also sorted out.
> Fix for potential DOM XSS

- admin/handlers/json-nodes.go
- admin/templates/table.html
Implementation of #104, display enrollment time for nodes in table
> Display enrollment time for nodes in table

- admin/handlers/go.mod
- admin/main.go
- api/main.go
- cli/main.go
- go.mod
- osctrl-api.yaml
- tls/handlers/go.mod
- tls/main.go
> Cutting v0.2.4

- admin/handlers/go.mod
- admin/main.go
- api/main.go
- cli/main.go
- go.mod
- osctrl-api.yaml
- tls/handlers/go.mod
- tls/main.go
> Release v0.2.5

- admin/handlers/post.go
- admin/handlers/templates.go
- admin/handlers/types-requests.go
- admin/handlers/types-templates.go
- admin/main.go
- admin/static/js/profile.js
- admin/static/js/users.js
- admin/templates/components/page-header.html
- admin/templates/profile.html
- admin/templates/users.html
- users/permissions.go
Implementation of #120 and allowing users to change their password, change their full name, and email and admins to change the password for users and also change full name, email and default environment:
> Profile edit and password change for users

- admin/handlers/json-queries.go
- admin/handlers/post.go
- admin/handlers/templates.go
- admin/handlers/types-requests.go
- admin/handlers/types-templates.go
- admin/main.go
- admin/static/css/custom.css
- admin/static/js/query.js
- admin/templates/components/page-aside-left.html
- admin/templates/components/page-modals.html
- admin/templates/queries-run.html
- admin/templates/saved.html
- queries/queries.go
- queries/saved.go
Implementation of #132 to save an on-demand query when the query is created to run. Future work would be to allow the query to be re-issued by target.
> Save on-demand queries when created

- tags/go.mod
Hopefully last follow up on https://github.com/jmpsec/osctrl/pull/152 and #151
> Migration to new JWT library

- Vagrantfile
Implementing #33 and adding support for the VMWare vagrant provider.
> Adding support for VMWare vagrant provider

- Makefile
Adding commands in the `Makefile` to display logs for each component.
> Makefile commands for docker logs

- admin/templates/carves-details.html
- carves/carves.go
- logging/process.go
- tls/handlers/carves.go
- tls/handlers/handlers.go
- types/osquery.go
Implementing the fix for #157 to restore the file carving functionality for osquery `5.0.1` and higher.
> Fix for file carving bug

- admin/handlers/go.mod
- admin/main.go
- api/main.go
- cli/main.go
- go.mod
- tls/handlers/go.mod
- tls/main.go
- version/go.mod
- version/version.go
Using just a single file to manage version for all components.
> Single file to manage version number

- admin/main.go
- api/main.go
- tls/main.go
Default file was incorrect for using external JSON configuration file for service and backend.
> Using correct default file for parameters

- cli/environment.go
- cli/main.go
- cli/node.go
- cli/query.go
- cli/settings.go
- cli/tag.go
- cli/user.go
- go.mod
- go.sum
- tls/main.go
Using https://github.com/urfave/cli v2
> Upgrading osctrl-cli to use urfave cli v2

- logging/logging.go
- logging/none.go
Adding logger as `none` that does not log data anywhere.
> Adding logger that does not log anything

- go.mod
- go.sum
- logging/kinesis.go
- logging/logging.go
- settings/settings.go
Adding `osctrl-tls` logger for `kinesis` for status, result and query logs
> Adding status, result and query logger for kinesis

- environments/scripts.go
- tools/packages/osx/postinstall
- tools/packages/osx/preinstall
Follow up to close off #220 completely
> Remaining updates for plist `io.osquery.agent.plist`

- Vagrantfile
- cli/settings.go
- deploy/config/systemd.service
- deploy/lib.sh
- deploy/provision.sh
- tls/main.go
- tools/packages/linux/osquery.flags
- tools/packages/osx/osquery.flags
* Fix for #221 
* Other improvements for `provision.sh`
> Improvements and fixes for provision

- cache/cache.go
Implementation for #227 to skip the Redis password, if it is set to empty string.
> Skip redis password if empty

- admin/main.go
- api/main.go
* Cleaning up some old unused logging code
* Default password for Redis is empty if not specified
> Cleanup old code and empty password for redis by default

- deploy/cicd/Dockerfile-osctrl-cli
- environments/environments.go
- environments/util.go
- users/users.go
- utils/go.mod
- utils/http-utils_test.go
- utils/string-utils.go
- utils/string-utils_test.go
* Adding `UUID` field to users.
* Unit tests to utils package.
* Fix for `Dockerfile-osctrl-cli` and CICD
> Adding UUID to user and fix cli dockerfile

- .github/workflows/tagged-releases.yml
Using keypair to sign docker images
> Fix for signing GHA

- admin/handlers/templates.go
- admin/templates/node.html
- carves/carves.go
- cli/environment.go
- cli/main.go
- environments/environments.go
- logging/process.go
- nodes/ipaddress.go
- nodes/metadata.go
- nodes/names.go
- nodes/nodes.go
- tls/handlers/handlers.go
- tls/handlers/utils.go
- tls/handlers/utils_test.go
- utils/string-utils_test.go
- utils/utils.go
- utils/utils_test.go
Added the ability to collect how much data has been submitted from nodes into `osctrl-tls`.
> Collect data transferred from nodes into `osctrl-tls`

- admin/handlers/templates.go
- api/handlers-settings.go
- api/main.go
- osctrl-api.yaml
- settings/settings.go
- tools/api_testing.py
Adding support to read settings values from `osctrl-api`.
> API settings

- tools/README.md
- tools/api_testing.py
- tools/fake_news.py
Adding `README.md` for tools and adding `fake_news.py` as script to simulate load for `osctrl`.
> Update to tools

- .github/workflows/build_and_test_main_merge.yml
- .github/workflows/build_and_test_pr.yml
> Typo in GitHub Actions name

- cli/main.go
- cli/user.go
- cli/utils.go
Permissions displayed in `octrl-cli` which was missing.
> Showing user permissions with osctrl-cli

- admin/handlers/post.go
- cli/environment.go
- tags/tags.go
- tags/utils.go
- tls/handlers/handlers.go
Tags are created based on UUID, hostname, platform and environment, and nodes are autotagged on enrollment.
> Autotagging when node enrolls

- admin/handlers/get.go
- admin/handlers/handlers.go
- admin/handlers/post.go
- admin/handlers/types-templates.go
- admin/handlers/utils.go
- admin/main.go
- admin/settings.go
- admin/utils.go
- api/main.go
- api/settings.go
- carves/carves.go
- carves/db.go
- carves/s3.go
- carves/utils.go
- deploy/docker/conf/osctrl/admin/admin.json
- deploy/docker/conf/osctrl/tls/tls.json
- environments/flags.go
- settings/settings.go
- tags/tags.go
- tls/handlers/carves.go
- tls/handlers/handlers.go
- tls/main.go
- tls/settings.go
- types/types.go
- utils/string-utils.go
Instead of storing chunks of carved files and carves in the database, putting them in s3 would be more efficient and it will have a less performance impact.
> File carves to s3

- environments/flags.go
Incorrect struct field, it was making flags to not be generated correctly.
> Template fix for flags generation

- admin/handlers/post.go
- tags/tags.go
* Under certain circumstances, autotagging functionality would create an empty tag.
* Also, fix for incomplete autotagging on enrollment.
* More efficient code and refactored.
> Avoid empty tags and fix for autotagging

- environments/environments.go
- nodes/nodes.go
- tls/handlers/handlers.go
- tls/handlers/utils.go
Adding user_id to environment, and it will be copied to enrolled nodes.
> Adding user id to environments and enrolled nodes

- admin/handlers/post.go
- cli/environment.go
- environments/environments.go
- environments/flags.go
- environments/oneliners.go
- settings/settings.go
- tls/handlers/handlers.go
- tls/handlers/utils.go
- tls/main.go
- types/types.go
Setting up `osctrl-tls` to use `osctrld`
> Endpoints in osctrl-tls for osctrld

- admin/main.go
- carves/s3.go
- logging/logging.go
- logging/s3.go
- tls/main.go
- types/types.go
Adding the ability to provide s3 configuration via ENV variables.
> Adding env variables for s3 configuration

- admin/handlers/post.go
When creating a new environment, permissions are automatically added for the user creating it.
> Grant user access for newly created environment

- cli/environment.go
- deploy/config/service.json
- deploy/lib.sh
- deploy/provision.sh
- environments/scripts.go
- go.sum
- tls/handlers/utils_test.go
Random number of fixes:
* Fix for provisioning auto-enrolling.
* Service configuration `carver` definition.
* Template fix for osquery version and enroll script.
> Fix for provisioning and auto-enrolling and service config

- nodes/nodes.go
- queries/queries.go
- queries/saved.go
This column can be used to decorate results.
> Adding extra data column to nodes and queries

- admin/handlers/templates.go
- admin/handlers/types-templates.go
- admin/templates/components/page-aside-left.html
- carves/carves.go
- carves/db.go
- carves/utils.go
- nodes/utils.go
- tls/handlers/carves.go
- tls/handlers/handlers.go
* Using environment ID for carves and carve blocks.
* Adding metadata for the side left component
* Fix for archiving in local carves, skip using `/` and `\`
> Carves using environment id

- admin/handlers/get.go
- admin/handlers/post.go
- admin/handlers/templates.go
- admin/handlers/types-requests.go
- admin/static/js/users.js
- admin/templates/users.html
- users/permissions.go
- users/users.go
- users/utils.go
Ability to edit permissions using `osctrl-admin`
> Edit permissions in `osctrl-admin`

- api/handlers-users.go
- api/main.go
- cli/api-user.go
- cli/api.go
- cli/main.go
- cli/node.go
- cli/user.go
- users/users.go
Ability to get users using `osctrl-api` and `osctrl-cli`
> Retrieving users from `osctrl-api` using `osctrl-cli`

- cli/carve.go
- cli/environment.go
- cli/main.go
- cli/node.go
- cli/query.go
- cli/settings.go
- cli/user.go
* Better output for errors in `osctrl-cli`
* Better output for successful executions in `osctrl-cli`
* Adding `-s/--silent` flag to `osctrl-cli`
> Better errors in `osctrl-cli`

- admin/handlers/post.go
- api/handlers-nodes.go
- api/main.go
- cli/api-node.go
- cli/main.go
- cli/node.go
- nodes/nodes.go
- types/types.go
* Better error handling and messages in `osctrl-cli`
* Cleaning up a bit `osctrl-admin`
* Deleting nodes via `osctrl-api`
> Node actions in `osctrl-api`

- admin/handlers/post.go
- users/permissions.go
- users/utils.go
Better user management from `osctrl-admin`
> Edit permissions from `osctrl-admin`

- .github/workflows/build_and_test_main_merge.yml
- .github/workflows/build_and_test_pr.yml
- .github/workflows/create_tagged_releases.yml
> Update golang from v1.18.1 to 1.19.2

- .github/workflows/build_and_test_main_merge.yml
- .github/workflows/build_and_test_pr.yml
- .github/workflows/create_tagged_releases.yml
> Update container from ubuntu 20.04 to 22.04

- .gitignore
- api/handlers-login.go
- api/main.go
- cli/api-login.go
- cli/api.go
- cli/main.go
- cli/node.go
- cli/permission.go
- cli/query.go
- cli/settings.go
- cli/user.go
- go.mod
- go.sum
- types/types.go
Ability to login to `osctrl-api` using user credentials to retrieve the API token
> Login to `osctrl-api` using `osctrl-cli`

- users/permissions.go
- users/permissions_test.go
- users/users_test.go
Increasing code coverage in the `users` module.
> Unit test for users

- admin/handlers/post.go
Checking if returned permissions was empty
> Fix permissions adjustment

- environments/scripts.go
Better bash and handling osquery upgrade to osctrl supported version in the enroll one-liner
> Handle osquery upgrade in enroll oneliner

- environments/scripts.go
Some shell incompatibility errors were introduced in https://github.com/jmpsec/osctrl/pull/329, this is the fix
> Using sh instead of bash for better compatibility

- environments/scripts.go
Populating the correct `_OS` variable for enrolling
> Small fix for enroll.sh

- deploy/osquery/data/5.8.2.json
Adding support for osquery `5.8.2`
> Support for osquery 5.8.2

- api/handlers-settings.go
- api/main.go
Retrieving settings per service and environment
> Retrieve service settings via API

- README.md
Following https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge for the change
> Adding build badge from GitHub Action

- deploy/docker/conf/osctrl/cli/entrypoint.sh
> Fix typo in entrypoint.sh

- admin/main.go
New parameter for `osctrl-admin` to enable retry the connection to Redis/cache if it fails:
```
--redis-conn-retry value         Time in seconds to retry the connection to the cache, if set to 0 the service will stop if the connection fails (default: 7) [$REDIS_CONN_RETRY]
```
> Retry connection for Redis/cache

- admin/auth/go.mod
- admin/handlers/go.mod
- admin/sessions/go.mod
- api/handlers/go.mod
- backend/go.mod
- cache/go.mod
- carves/go.mod
- environments/go.mod
- go.mod
- logging/go.mod
- metrics/go.mod
- nodes/go.mod
- queries/go.mod
- settings/go.mod
- tags/go.mod
- tls/handlers/go.mod
- types/go.mod
- users/go.mod
- utils/go.mod
- version/go.mod
Using golang `1.21` in all modules
> Bumping golang version to 1.21 in modules

- logging/db.go
- types/osquery.go
Serialization should be able to handle both types
> Line in status logs can be number or string

- admin/oauth.go
- settings/settings.go
The first step to have OAuth authentication
> Base for oauth authentication

- .github/actions/build/binaries/action.yml
- .github/actions/build/docker/action.yml
- .github/actions/build/dpkg/action.yml
- .github/actions/tagged_release/docker/codesign/action.yml
- .github/actions/tagged_release/github/action.yml
- .github/actions/test/binaries/action.yml
- .github/workflows/build_and_test_main_merge.yml
- .github/workflows/build_and_test_pr.yml
- .github/workflows/create_tagged_releases.yml
- All actions updated to latest version
- Removed path from upload-artifacts due to causing errors
> Updates to actions and remove path for upload-artifacts

- .github/actions/build/dpkg/action.yml
Creating DEB packages for tagged and not tagged versions
> Difference between tagged and not when creating DEB packages

- cli/api.go
- cli/carve.go
- cli/environment.go
- cli/query.go
- cli/user.go
- users/users.go
More consistent output in `osctrl-cli`
> Small fixes in osctrl-cli for output messages

- deploy/lib.sh
- deploy/provision.sh
Metrics infrastructure should be setup separately from the `provision.sh` script.
> Removing metrics from the provision script

- admin/auth/auth.go
Prevent logging username and fix for code scanning alerts
> Removing code scanning alerts

- admin/static/js/users.js
- cli/user.go
- deploy/provision.sh
Some code left behind for the default environment changes.
> Cleanup for default env code

- admin/templates/queries-logs.html
- deploy/docker/conf/dev/air/.air-osctrl-admin.toml
- deploy/docker/conf/dev/air/.air-osctrl-api.toml
- deploy/docker/conf/dev/air/.air-osctrl-cli.toml
- deploy/docker/conf/dev/air/.air-osctrl-tls.toml
- deploy/docker/dockerfiles/Dockerfile-dev-admin
- deploy/docker/dockerfiles/Dockerfile-dev-cli
Some small tweaks in docker files, air configuration to ignore some directories and better message for query logs when no results available due to logger.
> Small changes to docker files and air configuration

- admin/handlers/templates.go
- admin/handlers/utils.go
- admin/main.go
- admin/templates/enroll.html
- settings/settings.go
Not only copy the values in `osctrl-admin` but also download the files directly.
> Adding buttons to download secret, cert and flags

- admin/templates/enroll.html
Little aesthetic changes in the `enroll.html` template
> Small changes to the enroll.html template

- tools/bruno/bruno.json
- tools/bruno/environments/get -environments--env--enroll--target-.bru
- tools/bruno/environments/get -environments--env--remove--target-.bru
- tools/bruno/environments/get -environments--env-.bru
- tools/bruno/environments/get -environments.bru
- tools/bruno/nodes/get -nodes--env--active.bru
- tools/bruno/nodes/get -nodes--env--all.bru
- tools/bruno/nodes/get -nodes--env--inactive.bru
- tools/bruno/nodes/get -nodes-node--identifier-.bru
- tools/bruno/nodes/post -nodes--env--delete.bru
- tools/bruno/platforms/get -platforms--env-.bru
- tools/bruno/platforms/get -platforms.bru
- tools/bruno/queries/get -all-queries--env-.bru
- tools/bruno/queries/get -carves--env---name-.bru
- tools/bruno/queries/get -carves--env-.bru
- tools/bruno/queries/get -queries--env---name-.bru
- tools/bruno/queries/get -queries--env--results--name-.bru
- tools/bruno/queries/get -queries--env-.bru
- tools/bruno/queries/post -carves--env-.bru
- tools/bruno/queries/post -queries--env-.bru
- tools/bruno/settings/get -settings--service---env-.bru
- tools/bruno/settings/get -settings--service--json--env-.bru
- tools/bruno/settings/get -settings--service--json.bru
- tools/bruno/settings/get -settings--service-.bru
- tools/bruno/settings/get -settings.bru
- tools/bruno/tags/get -tags--env-.bru
- tools/bruno/tags/get -tags.bru
- tools/bruno/users/get -users--username-.bru
- tools/bruno/users/get -users.bru
To test the `osctrl-api` component it may be a good tool the [bruno API client](https://www.usebruno.com/) so adding the collection to see if it helps for testing. It was just an import from the OpenAPI YAML file.
> Adding collection for the bruno API client

- cli/api-environment.go
- cli/api.go
- cli/environment.go
- cli/main.go
- deploy/docker/conf/osquery/entrypoint.sh
- deploy/provision.sh
Using the enroll actions added in https://github.com/jmpsec/osctrl/pull/492 from `osctrl-api` in `osctrl-cli`
> Enroll actions in cli using the API

- osctrl-api.yaml
Rename the handler function after the refactor in #507
> Update to OpenAPI yaml to reflect the osctrl-api refactor

- tls/handlers/post.go
Better output logs in `osctrl-tls` and improvement in HTTP returned codes
> Better HTTP responses in osctrl-tls

- tools/bruno/environments/get -environments--env--remove--target-.bru
- tools/bruno/environments/post -environments--env--enroll--action-.bru
- tools/bruno/environments/post -environments--env--enroll--target-.bru
- tools/bruno/environments/post -environments--env--remove--action-.bru
Keeping the [bruno API client](https://www.usebruno.com/) up to date with the OpenAPI YAML file, for the `osctrl-api`.
> Keeping bruno files up to date to osctrl-api definition

- admin/static/js/configuration.js
- admin/templates/components/page-modals.html
- admin/templates/conf.html
- admin/templates/tags.html
- logging/process.go
Small enhancement in the `osctrl-admin` UI to avoid editing JSON directly.
> Modal in osctrl-admin to add a new query to schedule

- admin/handlers/go.mod
- admin/handlers/go.sum
- admin/sessions/go.mod
- api/handlers/go.mod
- api/handlers/go.sum
- backend/go.mod
- backend/go.sum
- cache/go.mod
- cache/go.sum
- carves/go.mod
- carves/go.sum
- environments/go.mod
- go.mod
- go.sum
- logging/go.mod
- logging/go.sum
- metrics/go.mod
- metrics/go.sum
- queries/go.mod
- settings/go.mod
- tags/go.mod
- tls/handlers/go.mod
- tls/handlers/go.sum
- types/go.mod
- users/go.mod
Running `go mod tidy` before cutting new release.
> Dependencies after go mod tidy

- admin/handlers/go.mod
- admin/sessions/go.mod
- api/handlers/go.mod
- cache/go.mod
- carves/go.mod
- environments/go.mod
- metrics/go.mod
- queries/go.mod
- settings/go.mod
- tags/go.mod
- tls/handlers/go.mod
- types/go.mod
- users/go.mod
Running `go mod tidy` after release.
> Dependencies bump after release

- api/main.go
Better info messages to track service start in `osctrl-api`
> Better info messages starting osctrl-api

- admin/handlers/go.mod
- admin/handlers/go.sum
- admin/sessions/go.mod
- admin/sessions/go.sum
- api/handlers/go.mod
- api/handlers/go.sum
- backend/go.sum
- cache/go.mod
- carves/go.mod
- environments/go.mod
- logging/go.sum
- queries/go.mod
- settings/go.mod
- tags/go.mod
- tls/handlers/go.mod
- tls/handlers/go.sum
- types/go.mod
- users/go.mod
Mitigation for `CVE-2024-45337`, more info: https://github.com/golang/go/issues/70779
> Update to x/crypto to mitigate CVE-2024-45337

- admin/templates/table.html
Some platforms reported by osquery may cause errors in datatables. This PR prevents those.
> Avoid datatables errors with platform field

- api/main.go
- osctrl-api.yaml
Updating the OpenAPI YAML file with the changes landed in #594 and #596
> Updating OpenAPI YAML file with latest changes in `osctrl-api`

- Makefile
- cmd/admin/handlers/post.go
- cmd/api/main.go
- cmd/api/utils.go
- cmd/cli/carve.go
- cmd/cli/node.go
- cmd/cli/permission.go
- cmd/cli/query.go
- cmd/cli/tag.go
- cmd/cli/user.go
- cmd/tls/handlers/utils.go
- pkg/carves/utils.go
- pkg/logging/kafka.go
- pkg/logging/kinesis.go
- pkg/settings/settings.go
- pkg/utils/string-utils.go
* Last remaining changes from running `golangci-lint run`
* Removed `gofmt` from `Makefile` and added `make lint` with the `golangci-lint run` command
> Last refactor changes from `golangci-lint run`

- .github/workflows/golangci-lint.yml
- .golangci.yml
Running `golangci-lint` on new Pull Requests.
> Adding GitHub Action to run `golangci-lint` on PRs

- docker-compose-dev.yml
Using `console` log format for docker dev environment.
> Using console log format for docker dev environment

- go.mod
- go.sum
Follow up PR after #622 to make sure there are no indirect references.
> Executed `go mod tidy` after migrating to config pkg

- cmd/admin/auth.go
- cmd/admin/handlers/handlers.go
- cmd/admin/handlers/types-templates.go
- cmd/admin/handlers/utils.go
- cmd/admin/main.go
- cmd/admin/settings.go
- cmd/tls/main.go
- cmd/tls/settings.go
- pkg/config/flags.go
- pkg/config/types.go
- pkg/logging/logging.go
- pkg/settings/settings.go
Big refactor in `osctrl-admin` and some small changes in `osctrl-tls` to utilize the config pkg for flags and configuration of services.
> Using new flags from config pkg in `osctrl-admin`

- pkg/queries/queries.go
- pkg/queries/queries_test.go
When a query is marked as expired, the relationship in the `node_queries` table isn't updated, causing osquery nodes to still receive expired queries.
Address a bug related to expired distributed queries and implement tests for the `SetNodeQueriesAsExpired` function, including a test for invalid query IDs. Refactor existing tests for improved clarity and maintainability.
> Fix expired distributed queries and enhance testing

- .github/actions/tagged_release/docker/codesign/action.yml
- .github/workflows/create_tagged_releases.yml
Using `cosign` keyless to sign images and bump to latest release
> Use cosign keyless to publish docker images

- .github/actions/build/docker/action.yml
- .github/actions/tagged_release/docker/codesign/action.yml
- .github/workflows/create_tagged_releases.yml
- .github/workflows/golangci-lint.yml
Fix for tagged release Docker image signing and other improvements
> Multiple fixes to tagged release GHA

- .github/actions/build/binaries/action.yml
- .github/actions/build/docker/action.yml
- .github/actions/build/dpkg/action.yml
- .github/actions/tagged_release/docker/codesign/action.yml
- .github/actions/tagged_release/github/action.yml
- .github/actions/test/binaries/action.yml
- .github/workflows/build_and_test_main_merge.yml
- .github/workflows/build_and_test_pr.yml
- .github/workflows/create_tagged_releases.yml
- .github/workflows/golangci-lint.yml
Bump all actions to latest version and pin to commits.
> Update all actions to latest version and pin to commit

- .github/actions/tagged_release/github/action.yml
- .github/workflows/create_tagged_releases.yml
- More detailed matrix for releases
- Keep going even if it fails, so other releases will be published
> More accurate releases matrix

- cmd/admin/handlers/get.go
- cmd/admin/handlers/json-carves.go
- cmd/admin/handlers/json-logs.go
- cmd/admin/handlers/json-nodes.go
- cmd/admin/handlers/json-queries.go
- cmd/admin/handlers/json-stats.go
- cmd/admin/handlers/json-tags.go
- cmd/admin/handlers/post.go
- cmd/admin/handlers/templates.go
- cmd/admin/handlers/tokens.go
Small typo in `osctrl-admin` error message
> Typo in `osctrl-admin` error message

- cmd/admin/handlers/post.go
- cmd/admin/static/js/users.js
- cmd/admin/templates/users.html
- cmd/api/handlers/users.go
- cmd/api/main.go
- cmd/cli/api-user.go
- cmd/cli/main.go
- cmd/cli/user.go
- osctrl-api.yaml
- pkg/types/types.go
- pkg/users/users.go
Potential fix for #689 and more improvements on how user are handled in `osctrl-api` and `osctrl-cli` and some fixes in `osctrl-admin`.
> Improvements to user management in `osctrl-api`, `osctrl-cli` and `osctrl-admin`

- README.md
Updating link to get an invite to osquery's Slack
> Updated slack link to osquery

- cmd/admin/handlers/templates.go
- cmd/admin/handlers/tokens.go
- cmd/admin/handlers/types-templates.go
- cmd/admin/static/js/profile.js
- cmd/admin/templates/carves-details.html
- cmd/admin/templates/carves-run.html
- cmd/admin/templates/carves.html
- cmd/admin/templates/components/page-aside-right.html
- cmd/admin/templates/components/page-header.html
- cmd/admin/templates/conf.html
- cmd/admin/templates/dashboard.html
- cmd/admin/templates/enroll.html
- cmd/admin/templates/environments.html
- cmd/admin/templates/node.html
- cmd/admin/templates/profile.html
- cmd/admin/templates/queries-logs.html
- cmd/admin/templates/queries-run.html
- cmd/admin/templates/queries.html
- cmd/admin/templates/saved.html
- cmd/admin/templates/settings.html
- cmd/admin/templates/table.html
- cmd/admin/templates/tags.html
- cmd/admin/templates/users.html
- pkg/environments/environments.go
- pkg/environments/osqueryconf.go
- pkg/environments/util.go
Fix for #705 to display each user their tokens in the user profile within `osctrl-admin`
> Show tokens in username profile

- cmd/admin/main.go
- cmd/api/main.go
- cmd/tls/main.go
- pkg/config/flags.go
- pkg/config/types.go
More progress towards implementing #644 and also adding configuration values for #703
> More progress for YAML single configuration

- cmd/admin/handlers/post.go
- cmd/admin/handlers/templates.go
- cmd/api/handlers/tags.go
- cmd/cli/api-tag.go
- cmd/cli/main.go
- cmd/cli/tag.go
- pkg/tags/tags.go
- pkg/tags/utils.go
- pkg/tags/utils_test.go
Multiple fixes for bugs and improving code in general around using tags in `osctrl-admin`, `osctrl-api` and `osctrl-cli`
> Multiple fixes using tags in `osctrl-admin`, `osctrl-api` and `osctrl-cli`

- tools/.gitignore
- tools/fake_news_go/MONITORING_GUIDE.md
- tools/fake_news_go/README.md
- tools/fake_news_go/fake_news.go
Adding a new tool to run performance testing using goroutines
> Adding fake_news.go to simulate load efficiently
