jmpsec/osctrl

cmd/admin/handlers-post.go, cmd/admin/handlers.go, cmd/admin/main.go, cmd/admin/static/js/enrolls.js, cmd/admin/templates/components/page-modals.html, cmd/admin/templates/enroll.html, cmd/admin/types-requests.go, cmd/tls/handlers-tls.go, cmd/tls/main.go, pkg/environments/environments.go, pkg/environments/flags.go
Several changes added in this PR:
* Environment certificate can be uploaded from the admin UI.
* Flags will be re-generated when changes are made to intervals.
* Default intervals are increased.
* Added health check for for `osctrl-tls` and `osctrl-admin` so it can be easy to monitor using things like k8s.
* Attempting to save an empty configuration will throw an error.
=> Upload certificate from admin and regenerate flags

cmd/admin/handlers-get.go, cmd/admin/handlers-post.go, cmd/admin/templates/environments.html, cmd/tls/handlers-tls.go, cmd/tls/main.go, pkg/environments/environments.go, pkg/environments/flags.go, plugins/logging_dispatcher/control.go, plugins/logging_dispatcher/db.go, plugins/logging_dispatcher/logging.go
* Added extra debug logging to the logging plugins.
* Splunk and Graylog plugins were never initialized despite the configuration being loaded. That was throwing a panic when using any of those plugins.
* Metadata for nodes is updated before logging, so in the case the plugins crashes, the metadata will be up to date.
* Removing flag `--tls_dump`.
* Adding flag `--distributed_tls_max_attempts`.
* Random clean-up code.
=> Logging plugins fixes and random stuff

cmd/admin/auth.go, cmd/admin/handlers-get.go, cmd/admin/handlers-post.go, cmd/admin/handlers.go, cmd/admin/json-carves.go, cmd/admin/json-logs.go, cmd/admin/json-nodes.go, cmd/admin/json-queries.go, cmd/admin/templates/carves-details.html, cmd/admin/templates/carves-run.html, cmd/admin/templates/carves.html, cmd/admin/templates/components/page-header.html, cmd/admin/templates/components/page-sidebar.html, cmd/admin/templates/conf.html, cmd/admin/templates/enroll.html, cmd/admin/templates/environments.html, cmd/admin/templates/node.html, cmd/admin/templates/queries-logs.html, cmd/admin/templates/queries-run.html, cmd/admin/templates/queries.html, cmd/admin/templates/settings.html, cmd/admin/templates/table.html, cmd/admin/templates/users.html, cmd/admin/types-templates.go
* Code to make possible having users in `osctrl-admin` that only see information, but can not take any actions such as run queries, run carves, delete nodes, change settings, change environments, modify users, change configuration, change intervals or modify enrolling links or certificates.
* Better metrics around JSON distribution endpoints.
* When visiting a node, the environment collapsible stays open.
=> Separation between users and admins

cmd/admin/handlers-post.go, cmd/admin/static/js/users.js, cmd/admin/templates/users.html, cmd/admin/types-requests.go, cmd/cli/main.go, cmd/cli/user.go, go.mod, pkg/queries/go.mod, pkg/types/go.mod, pkg/users/users.go, plugins/db_logging/go.mod, plugins/graylog_logging/go.mod, plugins/logging_dispatcher/go.mod, plugins/splunk_logging/go.mod
* Adding email to user record.
* Ability to add the email from the user creation modal.
* Ability to add/edit the email from `osctrl-cli`.
=> Adding email to users

cmd/admin/auth.go, cmd/admin/saml.go, cmd/admin/static/css/custom.css
* Adding `loginurl` field in the `saml.json` configuration, to provide the login URL to redirect to, if the session is expired or there is an error parsing the JWT token.
* Make login logo image a bit smaller.
=> Redirect to SAML login

cmd/admin/auth.go, cmd/admin/headers.go, cmd/admin/main.go, pkg/types/types.go
This adds more of the code needed to properly authenticate a user based on headers present added by a reverse proxy.
I'm wary of the CSRF token line that's commented out but I must just be missing something there. Also updating users always fails and I assume that's because the login flow never runs with header authentication.
The way this is designed to work is to be put behind a proxy that handles the authentication for you that then passes the request along with newly added trusted headers from the proxy.
Admin vs User level permissions are handled by checking for the presence of specified groups passed along from the proxy.
=> Improve the Header Authentication Method

docker/dockerize.sh
There has been a problem with `make docker_all` spotted by a couple of people (#9 and #18) and it seems that the folders `certs` and `config` was not created before running the command. This should fix that.
=> Create directories for docker certs and config

plugins/graylog_logging/plugin.go, tools/fake_logging.py
* Fix for #17 reported by @kosborn and when using the `graylog` logging option, the grouping of messages was making Graylog to not process the messages correctly.
* Also added a tool to test logging using HTTP requests (graylog, splunk...), that implementes a basic HTTP catch-all.
=> Graylog fix and logging test tool

plugins/graylog_logging/plugin.go
The objects for type `status` and `result` differ, and `result` was not being converted to JSON.
Duplicated code from the Splunk plugin https://github.com/jmpsec/osctrl/blob/master/plugins/splunk_logging/plugin.go#L42
Validated that it works in GrayLog.
=> Fixed Graylog plugin not sending `result`

cmd/api/main.go, docker/dockerize.sh
There is an error in the generated `api.json`. 
`"db"` is not a valid option in validLogging in `api/main.go:102`
```
var validLogging = map[string]bool{
settings.LoggingNone: true,
}
```
This was the error I got:
```
~/g/osctrl ❯❯❯ docker logs -f 0593dd8239167c3cc113779241b4cfc59896b9dbb1e19a0d603ffdf5ce926459
Postgres is up - Starting osctrl-api
main.go:109: Loading config/api.json
main.go:153: Error loading config/api.json - Invalid logging method: 'db'
Postgres is up - Starting osctrl-api
main.go:109: Loading config/api.json
main.go:153: Error loading config/api.json - Invalid logging method: 'db'
```
Nit: adding method in error strings to help with debugging.
=> bug: fix invalid logging method for api, default to none

cmd/admin/handlers-get.go
- Define a new structure to generate the filepaths
- No logic change
Testing...
Reload each page, but if there is another way let me know.
=> small refactor: to use struct for html layout pages

utils/utils.go
Using custom User Agent for the HTTP requests sent with `osctrl`. Since `osctrl` uses the native `net/http`, the User Agent is `Go-http-client/1.1` as you can see in [https://golang.org/src/net/http/request.go](https://golang.org/src/net/http/request.go)
This PR changes the default User Agent for `osctrl-http-client/1.1`.
=> Using custom user-agent

Makefile
Adding static compilation targets in the `Makefile`. This will help, for example, when deploying osctrl in a multi-stage docker image, where the build will require to be static so it can be used in minimal environments, for example, scratch images.
=> Compile osctrl statically

admin/main.go, api/main.go, cli/main.go, go.mod, logging/go.sum, queries/go.mod, tls/main.go, types/go.mod
Release of `0.2.0`. Lots of changes:
* Fixed Graylog plugin not sending `result`- #25 by @kosborn 
* Adding `osctrl-api` component - #28 
* Log distributed queries results locally - #30 
* Hidding API queries - #31 
* Bugfix: Invalid logging method for api, default to none - #34 
* Refactor: to use struct for html layout pages - #35 by @friedbutter 
* Productionalize `osctrl-api` - #36 
* No more plugins - #37 
* Using custom User Agent for HTTP requests - #39
* Make services wait for backend - #40 
* Preparing for osquery `4.2.0` - #41 
* Compile osctrl statically - #42 
Being the biggest change the introduction of `osctrl-api` and the removal of logging plugins.
=> Bump to osctrl 0.2.0

admin/handlers-post.go, admin/handlers-tokens.go, admin/handlers.go, admin/json-carves.go, admin/json-logs.go, admin/json-nodes.go, admin/json-queries.go, admin/json-stats.go, admin/templates/carves.html, admin/templates/components/page-aside-left.html, admin/templates/node.html, admin/templates/queries-run.html, admin/templates/queries.html, admin/templates/table.html, admin/utils.go, api/handlers-environments.go, api/handlers-nodes.go, api/handlers-platforms.go, api/handlers-queries.go, api/handlers.go, api/utils.go, deploy/osquery/osquery-dev.json, tls/carving.go, tls/handlers-tls.go, tls/logs.go, utils/utils.go
* Refactoring the way that an HTTP response is done. 
* Better metrics.
=> Refactor http responses

Makefile, go.sum, utils/go.mod, utils/go.sum, utils/http-utils.go, utils/http-utils_test.go, utils/time-utils.go, utils/time-utils_test.go
* Adding tests for module `utils`.
* Adding testing for modules in `Makefile`.
=> Adding tests for utils

admin/auth.go, admin/handlers-get.go, admin/handlers-post.go, admin/handlers-tokens.go, admin/json-carves.go, admin/json-logs.go, admin/json-nodes.go, admin/json-queries.go, admin/json-stats.go, admin/sessions.go, admin/templates/components/page-aside-left.html, users/permissions.go
* Ability to combine permissions and apply them to templates.
* Better code for checking permissions.
=> Permissions in templates and refactor

cli/environment.go
* Fix for #56 when flags were not updated when updating an environment using `osctrl-cli`.
=> Refresh flags on environment updates

cli/environment.go, cli/user.go
Fix for #55 to display when something was done with `osctrl-cli`.
=> Show message when something is done

deploy/lib.sh, deploy/provision.sh
The `provision.sh` deployment utility now allows to upgrade an existing deployment of `osctrl`, with the same abilities to customize which component to upgrade.
Quick example, this is how to upgrade all components (`admin`, `api`, `tls`) with the git repo clone in `/home/user/osctrl` and deployed in `/srv/osctrl`:
```
$ ./deploy/provision.sh -U -s /home/user/osctrl -S /srv/osctrl
```
=> Upgrade osctrl via provision

admin/main.go, api/main.go, environments/environments.go, logging/db.go, settings/settings.go, tls/main.go
Implementing #19 to keep logs locally in the database for a number of hours or number of entries.
* Added option to enable the removal of status logs, called `clean_status_logs` and also `clean_status_interval` as integer which will have the number of *seconds* to hold status logs for in the backend.
* Added option to enable the removal of result logs, called `clean_result_logs` and also `clean_result_interval` as integer which will have the number of *seconds* to hold result logs for in the backend.
* Added option to enable the removal of queries, query logs, query executions and query targets, called `clean_query_logs` and also `clean_query_entries` as integer which will have the number of *entries* to hold queries in the backend.
⚠️  If you enable this settings, and you do not have an …
=> Limit local status and result logs and queries

Makefile, deploy/docker/dockerize.sh
Fix for #67 when the utility `dockerize.sh` was using the wrong path for the `jwt.json` template and therefore, the deployment using docker was failing. Also there was an error in the path in `make docker_clean` so the generated configuration files were not removed.
=> Fix for error generating jwt.json

deploy/docker/dockerize.sh, deploy/docker/tls/Dockerfile
Second attempt to fix #71 where the files needed for the quick enroll were missing in the `osctrl-tls` container. This was only affecting the docker deployment.
=> Fix for docker enroll

deploy/lib.sh
Upgrading Grafana to `6.7.4` following security patches:
https://grafana.com/blog/2020/06/03/grafana-6.7.4-and-7.0.2-released-with-important-security-fix/
=> Upgrade to grafana 6.7.4

admin/handlers/go.mod, admin/main.go, admin/settings.go, api/main.go, cli/main.go, go.mod, tls/handlers/go.mod, tls/main.go
Release of `0.2.3`. List of changes:
- Fix for #71: Quick enroll using osctrl-admin - #72 
- Fix for #71: Docker quick enroll - #73 
- Implementation of #69: Ability to tag nodes - #74 
- Support for osquery [4.4.0](https://github.com/osquery/osquery/releases/tag/4.4.0) - #80 
- Fix for #82: UUIDs bug when receiving logs - #83 
- Change license from GPLv3 to MIT - #84 
- Upgrade to [Grafana](https://grafana.com/) 6.7.4 - #85 
- Support for osquery [4.5.1](https://github.com/osquery/osquery/releases/tag/4.5.1) - #91
=> Bump osctrl to 0.2.3

osctrl-api.yaml
Adding OpenAPI 3.01 YAML file for he documentation of `osctrl-api`. You can find the generated documentation in Swagger:
[https://app.swaggerhub.com/apis-docs/jmpsec/osctrl-api/](https://app.swaggerhub.com/apis-docs/jmpsec/osctrl-api/)
=> Adding API documentation

Vagrantfile, deploy/provision.sh
Ubuntu 20.04 LTS is now supported in `osctrl` using `provision.sh`. `Vagrantfile` also updated to build a local virtual machine with Ubuntu 20.04 using `vagrant up`.
=> Ubuntu 20.04 supported

deploy/lib.sh, deploy/provision.sh
`osctrl` builds now using go `1.15.6`
=> Upgrading to go1.15

Vagrantfile
The IP address when deploying `osctrl` using vagrant was static and was possible to change only editing the `Vagrantfile`. Now you can provide the ENV variable `OSCTRL_IP_ADDRESS` and it will be set, or defaults to the previous value that was `10.10.10.5`.
It can be utilized with the following command:
```
OSCTRL_IP_ADDRESS="10.10.10.6" vagrant up
```
...
```
...
default:
default: [+]  -> https://10.10.10.6:8443
default:
...
```
Also metrics have been disable in vagrant deployment.
=> Provide IP address as ENV variables for `Vagrantfile`

deploy/provision.sh
When using `provision.sh` using own certificates, which is with the parameter `-t own`, if the certificate and the key are only readable by root, their existence can not be verified and the provision will fail.
=> Fix for provision using own certificate

admin/auth.go, admin/auth/go.mod, admin/handlers/go.mod, admin/sessions/go.mod, api/handlers/go.mod, backend/go.mod, carves/go.mod, environments/go.mod, go.mod, go.sum, logging/go.mod, metrics/go.mod, nodes/go.mod, queries/go.mod, settings/go.mod, tags/go.mod, tls/handlers/go.mod, tls/handlers/go.sum, types/go.mod, users/go.mod, utils/go.mod
Bumping version to `go 1.15` in `go.mod` and also the saml package due to CVE. That includes refactoring some code that was changed with the upgrade.
=> Versions bump to go and saml pkg

deploy/docker/admin/wait.sh, deploy/docker/docker-compose.yml, deploy/docker/nodes/centos6/wait.sh, deploy/docker/nodes/centos7/wait.sh, deploy/docker/nodes/debian8/wait.sh, deploy/docker/nodes/debian9/wait.sh, deploy/docker/nodes/ubuntu16/wait.sh, deploy/docker/nodes/ubuntu20/Dockerfile, deploy/docker/nodes/ubuntu20/wait.sh, environments/flags.go, environments/go.mod, environments/go.sum, environments/oneliners.go, environments/oneliners_test.go, tls/handlers/handlers.go
The enroll one-liners that were generated with `osctrl` were forced to use insecure TLS connections which is not great. Now if the certificate for a new environment is empty, which happens when certificates like Let's Encrypt are used, no need to force insecure TLS with `curl -k` in shell or `[System.Net.ServicePointManager]::ServerCertificateValidationCallback = {$true};` in PowerShell.
Also added `ubuntu20` docker container for the dockerized dev environment and some improvements to the `wait.sh`.
=> Enroll one-liners can use proper certificates

admin/handlers/templates.go, admin/handlers/utils.go
Fix for #109 where an unprivileged user could see all environment names in the left panel of `osctrl-admin`
=> Fix for env name leaks for non-admins

deploy/provision.sh
When using the parameter `-U` o `--upgrade` in `provision.sh` to keep the running instance of `osctrl` up to date with `master`, this change will detect when there are untracked local changes before fetching remote.
=> Detect git changes when upgrading using `provision.sh`

deploy/lib.sh, deploy/provision.sh
When using `provision.sh` to upgrade an existing deployment of `osctrl`, copying existing files in `-m prod` was not working properly so this PR uses `rsync` instead.
=> Fix for upgrading existing osctrl

cli/environment.go, cli/main.go, cli/utils.go, environments/flags.go, environments/osqueryconf.go
Ability to add query packs, queries to existing query packs and other operations to edit the osquery configuration from `osctrl-cli` and `osctrl-admin`.
=> Add query packs from osctrl-cli

deploy/lib.sh, deploy/provision.sh
The command `rsync` was not issued recursively so some files were not getting updated.
=> Fix for updating existing osctrl

admin/handlers/json-logs.go, admin/templates/queries-logs.html
Implementation of #125 where system name nor `UUID` was shown on the results page for on-demand query that applied to multiple targets. For example using an environment or a platform.
Now results are shown with the localname and a link to the node:
=> Show target for on-demand query results

deploy/nginx/ssl.conf
Following https://github.com/osquery/osquery/pull/6910 and making sure that TLS 1.2 and 1.3 are default in `osctrl-nginx` because that is where the TLS termination happens.
=> TLS 1.2 and 1.3

admin/handlers/post.go, admin/handlers/types-requests.go, admin/templates/environments.html, environments/environments.go
Implementation of #119 and now the hostname for an existing environment is editable from `osctrl-admin`
=> Edit environment hostname from `osctrl-admin`

admin/jwt.go, go.mod, go.sum
Dependabot alert about `github.com/dgrijalva/jwt-go` JWT manipulation library:
```CVE-2020-26160
high severity
Vulnerable versions: <= 3.2.0
Patched version: No fix
jwt-go allows attackers to bypass intended access restrictions in situations with []string{} for m["aud"] (which is allowed by the specification). Because the type assertion fails, "" is the value of aud. This is a security problem if the JWT token is presented to a service that lacks its own audience check. There is no patch available and users of jwt-go are advised to migrate to golang-jwt at version 3.2.1```
Also some other changes due to `go mod tidy`
=> Migration to new JWT library

tls/main.go
Adding three new flags to `osctrl-tls`, to have the ability to serve HTTPS:
```
-cert string
Certificate file to be used for TLS. (default "config/tls.crt")
-key string
Private key file to be used for TLS. (default "config/tls.key")
-tls
TLS termination is enabled. It requires certificate and key.
```
=> Adding TLS/HTTPS support to `osctrl-tls`

api/main.go
Adding three new flags to `osctrl-api`, to have the ability to serve HTTPS:
```
-cert string
Certificate file to be used for TLS. (default "config/tls.crt")
-key string
Private key file to be used for TLS. (default "config/tls.key")
-tls
TLS termination is enabled. It requires certificate and key.
```
=> Adding TLS/HTTPS support to osctrl-api

admin/main.go
Adding three new flags to `osctrl-admin`, to have the ability to serve HTTPS:
```
-cert string
Certificate file to be used for TLS. (default "config/tls.crt")
-key string
Private key file to be used for TLS. (default "config/tls.key")
-tls
TLS termination is enabled. It requires certificate and key.
```
=> Adding TLS/HTTPS support to osctrl-admin

admin/main.go, admin/utils.go
Using [https://github.com/urfave/cli](https://github.com/urfave/cli) v2 adding support to use environment variables for all parameters that were loaded with JSON files.
=> Support for env variables for parameters in `osctrl-admin`

admin/main.go, tls/main.go
Values from environment values were not used in the configuration.
=> Use the values from env variables in `osctrl-tls`

admin/main.go, api/main.go
Using https://github.com/urfave/cli v2 adding support to use environment variables for all parameters that were loaded with JSON files.
=> Support for env variables for parameters in `osctrl-api`

admin/main.go, api/main.go, tls/main.go
* Fix for incorrect help message for `db-name`
* Loading configuration values into struct from parameters for `osctrl-tls`
=> Using correct help message and load config for osctrl-tls

admin/handlers/handlers.go, admin/handlers/templates.go, admin/handlers/utils.go, admin/main.go, admin/settings.go, admin/utils.go, api/main.go, api/settings.go, cli/main.go, deploy/config/service.json, deploy/docker/Dockerfile-osctrl-dev, deploy/docker/Dockerfile-osctrl-prod, deploy/docker/conf/osctrl/admin/admin.json, deploy/docker/conf/osctrl/api/api.json, deploy/docker/conf/osctrl/tls/tls.json, deploy/provision.sh, logging/db.go, logging/graylog.go, logging/logging.go, logging/splunk.go, tls/main.go, tls/settings.go, types/types.go, utils/http-utils.go
- Using new environment variable to specify the location for the logger configuration.
- Using single logger for status/result logs coming from nodes.
- Don't log to db logger regardless, only if it is enabled.
- Updated `provision.sh` to use the new configuration file.
- Updated docker configurations to use the new configuration file.
=> Using single logger and logger config file

go.mod, go.sum, logging/db.go, logging/go.mod, logging/go.sum, logging/graylog.go, logging/logging.go, logging/splunk.go, logging/stdout.go
Adding `stdout` logger capability to output logs in the standard output for the `osctrl-tls` service.
=> Adding status, result and query logger for stdout

admin/main.go, api/main.go
Fix for #209 and the correct env variable is used, `SERVICE_LOGGER`, to prevent the service attempting to load the default logger configuration file `config/logger.json`. Also for loggers that do not require external configuration (`none`, `stdout`, `file`) the error should not happen. Also affects `osctrl-api`.
=> Fix for #209 with osctrl-admin and osctrl-api using SERVICE_LOGGER

.github/workflows/build_and_test.yml, .github/workflows/tagged-releases.yml
Published DockerHub images are now signed using `cosign`. For more information:
https://github.blog/2021-12-06-safeguard-container-signing-capability-actions/
=> Adding signing capability to published docker images

admin/handlers/json-logs.go, admin/main.go, logging/db.go, logging/file.go, logging/logging.go, nodes/nodes.go
- Implementing fix for #209
- Creating DB logger using configuration struct or file
- Some cleanup
=> Fix for issue with db logger and osctrl-admin #209

admin/main.go, admin/sessions/sessions.go, api/auth.go, tls/handlers/handlers.go, types/types.go, utils/http-utils.go
- Added configuration parameter for `osctrl-admin` to provide an static session key so sessions won't reset after service restarts.
- Header constant for `X-Real-IP`
=> Provide session key in configuration

admin/sessions/sessions.go, api/auth.go, tls/handlers/handlers.go, utils/http-utils.go
Fix for #229 when using `osctrl` directly for TLS termination, without using nginx and `X-Real-IP` header is not present. Now it will check for `X-Real-IP`, `X-Forwarded-For` and of none of those are present, it will just capture the raw IP.
=> Fix for empty IP address when `X-Real-IP` not present

users/users.go
Implementation for #226 when both `osctrl-admin` and `osctrl-api` will not start if the JWT secret is not set properly.
=> Check JWT secret is not empty for `osctrl-admin` and `osctrl-api`

cli/main.go
Fix for #225 where `osctrl-cli` was crashing due to missing `cliWrapper` prefix to function.
=> Fix for crash showing environment secret

.gitignore, admin/handlers/handlers.go, admin/handlers/templates.go, admin/main.go, admin/templates/carves-run.html, admin/templates/carves.html, admin/templates/conf.html, admin/templates/enroll.html, admin/templates/environments.html, admin/templates/login.html, admin/templates/profile.html, admin/templates/queries-run.html, admin/templates/queries.html, admin/templates/saved.html, admin/templates/table.html, admin/templates/tags.html, admin/templates/users.html, deploy/docker/Dockerfile-osctrl-dev, deploy/docker/Dockerfile-osctrl-prod, deploy/provision.sh
Fix for #219 where online/offline static files (CSS and JS) had to be sym linked while provisioning. Now a new flag (`--static-offline`) is added to `osctrl-admin` to use offline assets, by default online assets are used.
=> Handle online or offline static files for `osctrl-admin`

tls/handlers/handlers.go, tls/handlers/utils.go
Implementation for #222 and more descriptive errors when returning one-liners responses. Also reducing the number of read queries to the backend for every request to `osctrl-tls`.
=> Better error messages for one-liners

deploy/lib.sh, deploy/provision.sh, deploy/redis/redis.conf
* Upgrade to go 1.18 for provision
* Cleanup for postgres installation
* Changes to redis configuration
=> Upgrade to go 1.18 and small changes to provision script

deploy/provision.sh
* Using the correct service name in Ubuntu for Redis
* CentOS provision should be manual
=> Redis service name update in Ubuntu

admin/main.go, cache/cache.go, deploy/provision.sh, logging/splunk.go, tls/main.go
* Expand list of allowed logging methods for `osctrl-tls`
* Configure systemd service properly to use external JSON for service configuration when using `provision.sh`
=> Using JSON file for config in provision

admin/main.go, api/main.go, cli/main.go, tls/main.go
Using environment variables with `osctrl-cli` similarly to other components
=> Using env variables with osctrl-cli

admin/handlers/post.go, admin/handlers/templates.go, admin/handlers/types-templates.go, admin/static/js/enrolls.js, admin/templates/enroll.html, environments/environments.go, environments/util.go, settings/settings.go, tls/main.go, tls/settings.go, utils/time-utils.go
* Ability to extend one-liners, for add and remove nodes, without changing them.
* Ability to rotate one-liners.
* Added new setting (`oneliner_expiration `) to `osctrl-tls` to allow one-liners never expire.
=> Extending and rotating one-liners

deploy/docker/conf/osctrl/cli/entrypoint.sh
The `osctrl-cli` component supports passing a password via an ENV var but not Docker secrets. This PR updates the entrypoint to support.
=> Updated osctrl-cli to support Docker secrets with OSCTRL_PASS_FILE

logging/logging.go, tls/main.go
* Always writing on-demand query results to database.
* Reduce accelerated mode to 60 seconds.
=> Always write on-demand query results to db

logging/db.go, logging/logging.go, tls/main.go
Adding ability to always log on-demand query logs and status.
This is configurable via parameters/environment variables:
```
--always-log, -a, --always             Always log status and on-demand query logs from nodes in database (default: false) [$ALWAYS_LOG]
--always-log-file value, --alog value  Database logger configuration to always store status and on-demand query logs from nodes (default: "config/always.json") [$ALWAYS_LOG_FILE]```
=> Adding always logger

CHANGELOG.md
Removing the compare because it will be added at the end of the release notes.
=> Small change to CHANGELOG

logging/logging.go, logging/utils.go, tls/handlers/utils_test.go, tls/main.go
* Fix for `osctrl-tls` unit tests.
* Prevent logging the same data twice, when always logging is enabled.
* Reuse the database configuration for always logging settings, so deployment is easier.
=> Prevent logging same data twice

environments/environments.go, nodes/nodes.go, tls/handlers/handlers.go, tls/handlers/utils.go
Adding `environment_id` to node table.
=> Environment ID added to node

queries/queries.go, queries/saved.go
Adding `environment_id` to saved and on-demand queries.
=> Environment ID added to queries

admin/main.go, api/main.go, tls/main.go
Fix for #265 in `osctrl-tls`, `osctrl-admin` and `osctrl-api`
=> Fix for #265 in tls, admin and api

cli/api-node.go, cli/api.go, cli/main.go, cli/node.go, cli/utils.go
Extend `osctrl-cli` to be used remotely via `osctrl-api` and authenticating via JWT tokens:
- Adding JSON output
- Adding CSV output
=> Using `osctrl-api` for nodes in `osctrl-cli`

cli/carve.go, cli/main.go, cli/node.go, cli/permission.go, cli/query.go, cli/user.go
* Better handling for permissions
* Using `-o / --output-format` for `json`, `csv` or `pretty` outputs
* Prepare `osctrl-cli` to utilize API for permissions
=> Improvements to `osctrl-cli`

deploy/cicd/docker/Dockerfile-osctrl-admin, deploy/cicd/docker/Dockerfile-osctrl-api, deploy/cicd/docker/Dockerfile-osctrl-cli, deploy/cicd/docker/Dockerfile-osctrl-tls, deploy/docker/Dockerfile-osctrl-dev, deploy/docker/README.md, deploy/docker/conf/osctrl/cli/entrypoint.sh, deploy/docker/conf/osquery/entrypoint.sh, docker-compose.yml
Updates:
- Update docker base image to ubuntu:22.04, 
- update osctrl-cli commands to use `osctrl-cli --db`, 
- updated entrypoint scripts
=> Update Docker setup for v0.3.1

logging/s3.go
Using the following hierarchy for s3 logs:
```
environment -> log type -> UUID:timestamp
```
=> Better hierarchy in s3 logs

deploy/docker/conf/osctrl/cli/entrypoint.sh, deploy/docker/conf/osquery/entrypoint.sh, deploy/docker/conf/osquery/wait-cli.sh, deploy/docker/conf/osquery/wait.sh, deploy/provision.sh
Using the newest syntax for `osctrl-cli`
=> Fix `osctrl-cli` syntax

logging/logging.go
Environment variables were not used properly for S3 configuration in loggers.
=> Using env variables for S3 configurations

docker-compose.yml
This fixes the error when running docker-compose build
```
$ docker-compose build
ERROR: Service "postgres" defines an invalid healthcheck: when "test" is a list the first item must be either NONE, CMD or CMD-SHELL
```
=> fix docker-compose build error

.github/actions/tagged_release/github/action.yml, .github/workflows/build_and_test_main_merge.yml, .github/workflows/build_and_test_pr.yml, .github/workflows/create_tagged_releases.yml
Background
Our CI/CD pipeline is not building Docker containers for Darwin arm64 (M1 macbooks). 
Changes
This PR instructs the CI/CD pipeline to build osctrl component for Linux (amd64, arm64), darwin (amd64, arm64), and osctrl-cli for Windows.
=> Build osctrl components for arm64 + darwin. Build osctr-cli for Windows

admin/handlers/get.go, admin/handlers/json-carves.go, admin/handlers/json-logs.go, admin/handlers/json-nodes.go, admin/handlers/json-queries.go, admin/handlers/json-stats.go, admin/handlers/json-tags.go, admin/handlers/post.go, admin/handlers/templates.go, admin/handlers/tokens.go, admin/settings.go, api/handlers-carves.go, api/handlers-environments.go, api/handlers-login.go, api/handlers-nodes.go, api/handlers-platforms.go, api/handlers-queries.go, api/handlers-settings.go, api/handlers-tags.go, api/handlers-users.go, api/handlers.go, api/settings.go, api/utils.go, cli/node.go, cli/settings.go, settings/settings.go, tls/settings.go, tls/utils.go
Big refactor, to prepare settings to be environment independent.
=> Preparing settings to be set by environment

admin/templates/components/page-aside-left.html, admin/templates/node.html, environments/util.go
Using `redhat` icon for Amazon Linux
=> Adding icon to amzn linux

.github/workflows/build_and_test_main_merge.yml, .github/workflows/create_tagged_releases.yml, deploy/lib.sh, deploy/provision.sh
Adding support for golang `1.21.3`
=> Support for golang 1.21.3

.github/workflows/build_and_test_main_merge.yml, .github/workflows/build_and_test_pr.yml, .github/workflows/create_tagged_releases.yml
More information in https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> Remove deprecated set-output

backend/backend.go, deploy/config/db.json, tls/main.go
New parameter for `osctrl-tls` to enable retry the connection to the DB if it fails:
```
--db-conn-retry value            Time in seconds to retry the connection to the database, if set to 0 the service will stop if the connection fails (default: 7) [$DB_CONN_RETRY]
```
=> Adding db connection retry

api/main.go
New parameter for `osctrl-api` to enable retry the connection to the DB if it fails:
```
--db-conn-retry value            Time in seconds to retry the connection to the database, if set to 0 the service will stop if the connection fails (default: 7) [$DB_CONN_RETRY]
```
=> Adding db connection retry in osctrl-api

cache/cache.go, tls/main.go
New parameter for `osctrl-tls` to enable retry the connection to Redis/cache if it fails:
```
--redis-conn-retry value         Time in seconds to retry the connection to the cache, if set to 0 the service will stop if the connection fails (default: 7) [$REDIS_CONN_RETRY]
```
=> Retry connection for Redis/cache

tls/main.go
This PR fixes the issue that if a value was passed as env variable or parameter, it was going to be rewritten by the default value expected from the JSON file in `osctrl-tls`.
=> Respect values from parameters vs. configuration files for `osctrl-tls`

admin/main.go
This PR fixes the issue that if a value was passed as env variable or parameter, it was going to be rewritten by the default value expected from the JSON file in `osctrl-admin`.
=> Respect values from parameters vs. configuration files in `osctrl-admin`

api/main.go
This PR fixes the issue that if a value was passed as env variable or parameter, it was going to be rewritten by the default value expected from the JSON file in `osctrl-api`.
=> Respect values from parameters vs. configuration files in `osctrl-api`

tags/go.mod, tags/go.sum, tags/utils.go, tags/utils_test.go
Removing the deprecated `rand.Seed` to use the latest method to seed random functions:
https://pkg.go.dev/math/rand@master#Seed
=> Remove deprecated `rand.Seed`

admin/auth.go, admin/handlers/get.go, admin/handlers/json-carves.go, admin/handlers/json-logs.go, admin/handlers/json-nodes.go, admin/handlers/json-queries.go, admin/handlers/json-stats.go, admin/handlers/json-tags.go, admin/handlers/post.go, admin/handlers/templates.go, admin/handlers/tokens.go, admin/main.go, admin/sessions/sessions.go, deploy/lib.sh
Use `token` for the cookie name, so it will follow the same name than the SAML library:
https://github.com/crewjam/saml/blob/main/samlsp/session_cookie.go#L11
=> Use token for cookie name

cli/environment.go, cli/main.go
Adding command in `osctrl-cli` to re-generate flags, based on the values for the environment, and save them:
```
gen-flags, g            Generate and save the flags for a TLS environment
```
=> Regenerate flags and save them

users/permissions.go
When listing environments, a user with admin permissions would not see the ones without explicit access to them.
=> Admin users can see all environments

admin/utils.go, cli/api.go, tls/handlers/handlers.go, utils/http-utils.go
`ioutil.ReadAll` is deprecated to `io.ReadAll` for go > 1.16
=> Changing ioutil.ReadAll to io.ReadAll

Makefile
Due to incorrect indentation, `Makefile` was incorrectly asking for files that were not needed.
=> Fix for Makefile indentation

admin/templates/node.html
Hiding the slider in the `osctrl-admin` view for status and results logs until that is fully operational in the backend.
=> Remove slider to select hours for status/results

admin/handlers/json-logs.go, logging/db.go, types/osquery.go
Serialization should be able to handle both types
=> Severity in status logs can be number or string

queries/queries.go
In certain scenarios, accelerated mode would activate when it should not. That would increase significantly the amount of query read requests from osquery. Disabling for now.
=> Disable accelerated mode handling query reads from osquery

admin/static/js/query.js, admin/templates/queries-logs.html, admin/templates/queries-run.html
External links without noopener/noreferrer are a potential security risk.
Specify the link type by adding an attribute`rel="noopener noreferrer"`.
=> Fix for potentially unsafe external link

.github/actions/build/dpkg/action.yml
Name for published DEB package was incorrect in tagged release.
=> Fix for deb package name in tagged release

.github/actions/build/binaries/action.yml
Binary name was incorrect on `go build` command
=> Fix for binary output on merged commits

deploy/cicd/deb/generate-deb-package.sh
Typo in variable name was missing the osctrl component
=> Fix for generate deb packages due to typo

.github/actions/build/docker/action.yml, .github/actions/build/dpkg/action.yml, .github/actions/tagged_release/docker/codesign/action.yml, .github/actions/tagged_release/github/action.yml, .github/actions/test/binaries/action.yml, deploy/cicd/deb/deb-conffiles, deploy/cicd/deb/post-init.sh, deploy/cicd/deb/pre-init.sh
- Actions bumped to latest version
- Fixed typo in parameter name
- Fix for action build-deb-action when deb is not a tagged version
=> Typos, more updates to actions and fix for untagged build-deb-action

deploy/lib.sh, deploy/provision.sh
Fix for https://github.com/jmpsec/osctrl/issues/412 to allow setup the backend in Ubuntu 20.04
=> Backend can be multiple versions of PostgreSQL

deploy/lib.sh, deploy/provision.sh
Some fixes for `provision.sh` to be able to deploy osctrl in Ubuntu 20.04 and Debian 12. Related with backend (postgres) and cache (redis).
=> Fix for provision script to support Ubuntu 20.04 and Debian 12

logging/logging.go, logging/logstash.go, settings/settings.go, tls/main.go, utils/go.mod, utils/go.sum, utils/http-utils.go
Adding new logger to `osctrl-tls` to send logs to Logstash via `tcp`, `udp` or `http`. The configuration would be like this:
```
{
"host": "127.0.0.1",
"port": "1234",
"protocol": "http",
"path": "/logging"
}
```
=> Sending TLS logs to logstash via tcp, udp or http

admin/oidc.go, settings/settings.go
`oidc` authentication in `osctrl-admin` is coming
=> Adding constants to prepare for OIDC auth

admin/auth/go.mod, admin/handlers/go.mod, admin/sessions/go.mod, api/handlers/go.mod, backend/go.mod, cache/go.mod, carves/go.mod, environments/go.mod, go.mod, logging/go.mod, metrics/go.mod, nodes/go.mod, queries/go.mod, settings/go.mod, tags/go.mod, tls/handlers/go.mod, types/go.mod, users/go.mod, utils/go.mod, version/go.mod
Until the migration to `1.22` let's keep the previous format.
=> Using 1.23 format for go.mod

admin/auth.go
Using the same cookie name than the samlsp library was causing some issues when `saml` was configured as authentication method in `osctrl-admin`.
=> Using different cookie name to avoid conflicts

deploy/provision.sh
Default path for code to be used in parameter `-s` in the `provision.sh` script is now `~/osctrl`.
=> Change default path for code in provision

deploy/lib.sh
Adding a helper function in the `lib.sh` file to create certificates for SAML authentication.
=> Helper function for SAML certificate

admin/auth.go, admin/main.go, admin/saml.go, admin/static/js/login.js
Two main things implemented here:
- Fix for SAML authentication and redirect loops.
- Implementation of JIT provisioning for accounts within osctrl.
=> Fix for SAML authentication and redirect loops

deploy/lib.sh
When using the `provision.sh` to provision a brand new server, it could fail for ARM due to downloading the wrong golang installer.
This was the error seen:
```line 412: /usr/local/go/bin/go: cannot execute binary file: Exec format error```
=> Install golang depending on architecture

deploy/redis/redis.conf
Adding an eviction policy to the default redis configuration, to avoid OOM issues.
=> Adding eviction policy to redis to avoid OOM issues

admin/handlers/json-logs.go, admin/handlers/templates.go, admin/handlers/types-templates.go, admin/handlers/utils.go, admin/templates/node.html, admin/templates/queries-logs.html, cache/cache.go, settings/settings.go
When trying to retrieve on-demand query results, or any other results that may be stored in the DB, the `osctrl-admin` service was invoking a `nil` pointer, causing a panic. This PR fixes several issues, including #438:
- Display a message when the logger is not configured to `db`, and there are no logs to display. 
- Making sure keys in redis are expired.
- The JSON setting for logger was not stored in the DB correctly.
=> Missing query results and `osctrl-admin` panics

.github/actions/build/docker/action.yml, .github/actions/build/dpkg/action.yml, .github/actions/tagged_release/docker/codesign/action.yml, .github/actions/tagged_release/github/action.yml, .github/workflows/build_and_test_main_merge.yml, .github/workflows/create_tagged_releases.yml
Add support for arm64 docker builds
- Split building images into 2 steps: one to build all images for all platforms and export the digests upstream; create the new image using all digests with `docker buildx imagetools create` as recommended in [multi-platform.md](https://github.com/crazy-max/docker-docs/blob/6aa26f53aeecf40013a3a255b36a8f21a08b0ac9/build/ci/github-actions/multi-platform.md)
- updated `.github/actions/tagged_release/docker/codesign/action.yml` to sign all images and digests pushed to docker hub
- Push `latest` tag on new tagged_releases
- use `docker/metadata-action` to tag the images 
- fixed bug in `.github/actions/tagged_release/github/action.yml` where `inputs.commit_sha` was missing from file name
- fixed bug in `.github/actions/build/dpkg/action.yml` where the …
=> Add support for arm64 docker builds

admin/handlers/handlers.go, admin/main.go, deploy/docker/dockerfiles/Dockerfile-dev-admin, deploy/docker/dockerfiles/Dockerfile-dev-api, deploy/docker/dockerfiles/Dockerfile-dev-tls, docker-compose-dev.yml, logging/logging.go, tls/main.go
Several things in this PR:
- Making sure the logger for the docker dev environment is set to `db`.
- Adding new parameter (`logger-db-same`) and env variable (`LOGGER_DB_SAME `) to use the same configuration for the logger than the backend access.
- Some small changes in the dockerfiles.
=> Logger for docker environment is set to db

environments/go.sum, environments/scripts.go
The one-liner shell script was using `dpkg` in `darwin` systems and making the script to fail with unexpected results. Added a function to prevent that.
=> Fix for enrollment one-liner using dpkg in darwin

Makefile
Adding commands in `Makefile` to only rebuild a single service. Very useful when doing local development.
=> Rebuilding single services in docker environment

api/main.go, osctrl-api.yaml
All data structures and routes updated to reflect the service
=> Up-to-date OpenAPI 3.0.1 YAML for osctrl-api

api/handlers-environments.go, api/main.go, osctrl-api.yaml, types/types.go
Implementation of #459 to retrieve enroll/remove values for an environment using `osctrl-api`. Also updates the YAML for OpenAPI.
=> Get enroll and remove values from API for an environment

api/postgres.go
Update type for Data as reflected here: https://github.com/jmpsec/osctrl/blob/main/logging/db.go#L54-L54
=> fix QsqueryQueryData Data type for query results api call

cli/main.go
Fix for #469 
Default setting for `osctrl-cli` was to use API instead of DB, so there were some panics due to nil pointers being referenced.
Changed to use DB instead, as default. Once all the modes support the `osctrl-api`, we can switch back to use API by default.
=> Setting database as default for osctrl-cli

environments/scripts.go
The one-liner for RPM based Linux will download the osquery package for the correct architecture.
=> Oneliner for RPM linux gets osquery by architecture

admin/handlers/post.go, admin/handlers/templates.go, admin/handlers/types-requests.go, admin/static/js/tags.js, admin/templates/tags.html, api/handlers-platforms.go, api/handlers-tags.go, api/main.go, cli/environment.go, environments/util.go, nodes/nodes.go, osctrl-api.yaml, tags/tags.go
In addition to adding to `osctrl-api` the ability to query tags and platforms by environment, this PR also adds `environment_id` to the tags table in the DB.
Keep in mind that existing tags won't have the value set, and the table `tagged_nodes` will need to be used to keep data integrity. Example of the SQL to be used:
```
UPDATE admin_tags a SET environment_id = (SELECT environment_id FROM osquery_nodes WHERE id = t.node_id) FROM tagged_nodes t;
```
=> Adding tags and platforms by environment in osctrl-api

backend/backend.go, deploy/config/db.json
Change underscore to camel case capitalization for the `db.json` configuration file. Here is the actual issue with the JSON parsing library:
https://github.com/spf13/viper/issues/678
=> Skip using underscore in DB JSON configuration file

Makefile
When issuing the command `make install_admin`, the directories for templates and static content were not refreshed in the destination directory. With this changes using `Makefile` helps to be more efficient.
=> Keep templates and static directories updated

admin/handlers/get.go, admin/handlers/go.mod, admin/handlers/json-carves.go, admin/handlers/json-logs.go, admin/handlers/json-nodes.go, admin/handlers/json-queries.go, admin/handlers/json-stats.go, admin/handlers/post.go, admin/handlers/templates.go, admin/handlers/tokens.go, admin/main.go
Using the new `http.NewServeMux()` introduced in go `1.22` and skip using third party dependencies such as gorilla/mux
=> Migration from gorilla mux to the native mux in osctrl-admin

admin/handlers/post.go
Make sure we keep consistent the path variable names in `osctrl-admin`
=> Keep path variable name consistent in osctrl-admin

admin/handlers/post.go, api/handlers-environments.go, api/main.go, settings/settings.go, types/types.go
Adding the ability to extend/expire/rotate/notexpire actions for enroll/remove nodes in `osctrl-api`
=> Perform actions to enroll-remove nodes in osctrl-api

Makefile
New command in `Makefile` to delete the osctrl images, handy when rebuilding the environment. Use it with `make docker_dev_clean`
=> Adding command to Makefile to cleanup osctrl docker images

api/handlers-environments.go, cli/api-environment.go, cli/environment.go, cli/main.go
Implementation of https://github.com/jmpsec/osctrl/issues/470
Adding commands to `osctrl-cli` to perform actions (extend/expire/rotate/notexpire) to enroll and remove URLs for nodes.
Fully supporting `osctrl-api`.
=> Adding commands to extend/expire/rotate enroll and remove URLs

api/handlers-environments.go, osctrl-api.yaml
To be used with the `osctrl-api` documentation in https://osctrl.net/openapi/doc.html
=> Update OpenAPI yaml with the enroll/remove actions endpoints

admin/handlers/post.go, admin/handlers/tokens.go, api/handlers-login.go, users/users.go, users/users_test.go
`jwt.StandardClaims` is deprecated so using `jwt.RegisteredClaims` instead. Also passing the token issuer as parameter.
=> Using RegisteredClaims in JWT to avoid deprecated code

environments/environments.go, tls/handlers/post.go
Using only the `UUID` identifier to be exposed via `osctrl-tls`
=> Using only UUID to identify environment in osctrl-tls

api/handlers/carves.go, api/handlers/environments.go, api/handlers/login.go, api/handlers/nodes.go, api/handlers/platforms.go, api/handlers/queries.go, api/handlers/settings.go, api/handlers/tags.go, api/handlers/users.go, api/main.go, nodes/nodes.go, osctrl-api.yaml
Using only the `UUID` identifier to be exposed via `osctrl-api`
=> Using only UUID to identify environment in osctrl-api

api/auth.go, api/handlers/carves.go, api/handlers/environments.go, api/handlers/login.go, api/handlers/nodes.go, api/handlers/platforms.go, api/handlers/queries.go, api/handlers/settings.go, api/handlers/tags.go, api/handlers/users.go, api/handlers/utils.go, api/jwt.go, api/main.go, api/settings.go, api/utils.go
Migrating `osctrl-api` to zerolog so logs are better formatted.
=> Migrating native log to zerolog in osctrl-api

deploy/lib.sh, deploy/provision.sh
Possibly fix for https://github.com/jmpsec/osctrl/issues/436
Check if user and database `osctrl` exist before creating.
=> Check for postgres user and database before creating

admin/handlers/json-carves.go, admin/handlers/json-queries.go, admin/handlers/post.go, admin/handlers/templates.go, admin/handlers/types-requests.go, admin/handlers/utils.go, admin/main.go, admin/settings.go, admin/static/js/carves.js, admin/static/js/query.js, admin/templates/carves-details.html, admin/templates/carves-run.html, admin/templates/queries-logs.html, admin/templates/queries-run.html, queries/queries.go, settings/settings.go
Adding expiration to distributed queries and carves, so they won't stay active all the time. Implements https://github.com/jmpsec/osctrl/issues/529
=> Distributed queries and carves do expire

logging/process.go, logging/utils.go, nodes/ipaddress.go, nodes/names.go, nodes/nodes.go
Fix for https://github.com/jmpsec/osctrl/issues/534
Username and other fields (hostname, localname, ipaddress...) were not updated when the results of decorators were returned to `osctrl-tls`.
=> Update username and other metadata from decorators

admin/templates/components/page-modals.html, logging/utils.go
When there was some mismatched metadata, the value `mismatched` could end up being written as a node's metadata. This prevents it.
=> Avoid replacing metadata values with the string mismatched

logging/utils.go
If the recorded metadata was different than the incoming metadata, incorrect updates could happen.
=> Fix for metadata updates done wrong on mismatch

logging/utils.go
Removing unnecessary logs when metadata mismatches happens.
=> Avoid spamming logs with unnecessary log entries for metadata mismatch

admin/handlers/post.go, admin/handlers/utils.go, api/handlers/carves.go, api/handlers/queries.go, queries/utils.go, types/types.go
Providing the expiration in hours, or no expiration if value is zero, using `osctrl-api`, for queries and carves.
=> Run queries and carves via osctrl-api with expiration

cli/api-carve.go, cli/api-query.go, cli/carve.go, cli/main.go, cli/query.go
Provide the expiration in hours when using `osctrl-cli` to run queries or carves.
=> Run queries and carves with expiration using osctrl-cli

api/handlers/carves.go, api/handlers/queries.go, api/main.go, osctrl-api.yaml, queries/queries.go, settings/settings.go
Executing `expire` and `delete` actions for on-demand queries and file carves, via `osctrl-api`. Also updated the YAML for OpenAPI with the new code.
=> Delete and expire carves and queries via osctrl-api

cli/api-carve.go, cli/api-query.go, cli/carve.go, cli/query.go, settings/settings.go
Utilizing `osctrl-api` with `osctrl-cli` to perform actions (delete/expire) in distributed queries and file carves.
=> Using osctrl-api by osctrl-cli for expire/delete queries and carves

api/auth.go, api/handlers/carves.go, api/handlers/environments.go, api/handlers/nodes.go, api/handlers/platforms.go, api/handlers/queries.go, api/handlers/settings.go, api/handlers/tags.go, api/handlers/users.go, api/handlers/utils.go
This pull request fixes a context type mismatch issue https://github.com/jmpsec/osctrl/issues/549 in the osctrl-api code. The `contextValue` and `contextKey` types have been renamed to `ContextValue` and `ContextKey` respectively to be used by `auth.go`.
=> Fix for osctrl-api context type mismatch

tls/handlers/metrics.go, tls/handlers/post.go
https://github.com/jmpsec/osctrl/issues/547
It will add the metrics and logs first, and then remove the direct writing to the database.
Here is an example of the average request size for different types:
=> Add metrics for size of ingested data

admin/handlers/json-queries.go, api/handlers/carves.go, api/handlers/queries.go, api/main.go, cli/api-carve.go, cli/api-query.go, cli/carve.go, cli/main.go, cli/query.go, osctrl-api.yaml, queries/queries.go
Multiple things implemented in `osctrl-api`, including fix for https://github.com/jmpsec/osctrl/issues/549
* Crash fix when attempting to run a query using `osctrl-api`
* List of targets when listing queries and carve queries
* Ability to list carve queries as well as carves
* Full support in `osctrl-cli` for all `osctrl-api` changes
* Updated OpenAPI YAML file
=> Multiple changes to osctrl-api: Crash fix, show carve queries and better targets to list queries

logging/elastic.go
Defining separator for index prefix and date and parsing events. This may end up being rewritten using the bulk API for elasticsearch but for now it stays like this.
=> Improvements to elastic logger for osctrl-tls

tls/main.go
Change the default logger configuration JSON in `osctrl-tls` to be `logger_tls.json` and small update to the service startup messages, to follow the same structure with `osctrl-admin` and `osctrl-api`.
=> Different default logger JSON in osctrl-tls and small change to startup messages

tools/.gitignore, tools/README.md, tools/build-osctrl-pkg.sh
Adding some extra functionality to the `build-osctrl-pkg.sh` script, now it can create a PKG file with or without osquery included.
=> Fixes for pkg builder script

admin/main.go, cache/cache.go, cache/utils.go, tls/main.go
Removing all references of logging status/result/query logs in cache/Redis, since it won't be enabled again as it was causing issues and it was just legacy code. Also removed the configuration parameters from JSON and `osctrl-admin` and `osctrl-tls` parameters for the same logging flags.
=> Cleanup code in cache for logs

admin/handlers/post.go, admin/handlers/tokens.go, admin/handlers/types-requests.go, admin/static/js/users.js, admin/templates/users.html, api/handlers/login.go, cli/api-login.go, cli/main.go, types/types.go, users/users.go, users/users_test.go
Provide the expiration in hours when creating a new `osctrl-api` token, using the `osctrl-admin` interface, or the `osctrl-cli` via the `osctrl-api`. If value is `0`, the value will be what is specified in the `hoursToExpire` field from the `jwt.json` file.
=> Specify expiration for tokens in osctrl-admin and osctrl-api

admin/main.go, api/main.go, tls/main.go, types/types.go
Introduce configuration options for log level and format in services, allowing customization of logging behavior. This change enhances the flexibility of logging by enabling different log levels and formats through command-line flags and environment variables.
The change was made for admin and api. For tls, I would like to discuss a better naming convention:
- We need a configuration for server's logs
- We need another logger configuration for exports logs and results from osquery
Also, the code are highly duplicated and I would like to remove the duplication.
For documentation, do you know where should update these configuration options?
=> Add log level and format configuration options for services

queries/queries.go
Fix for #577 
Schema for the table `node_queries` must be altered manually to expand its size. Use this query:
```
ALTER TABLE node_queries ALTER COLUMN status TYPE varchar (10);
```
This should resolve the issue.
=> Fix to prevent queries not completing

environments/flags.go, environments/flags_test.go
Adding a single flag to the generated flags for osquery.
=> Ability to add a single flag for osquery

admin/handlers/handlers.go, admin/jwt.go, admin/main.go, admin/oauth.go, admin/oidc.go, admin/saml.go, api/jwt.go, backend/backend.go, cache/cache.go, carves/s3.go, cli/api.go, logging/elastic.go, logging/graylog.go, logging/kinesis.go, logging/logstash.go, logging/s3.go, logging/splunk.go, metrics/metrics.go
When loading any JSON configuration file, if the key was missing, it would leave a nil pointer that could crash the service. This PR prevents that from happening.
=> Prevent nil pointer when loading any JSON configuration

admin/auth.go, admin/main.go, admin/saml.go
After the migration to the native `http.ServeMux`, the routes for the `/saml/` paths were only catching `GET` requests. It was making SAML to not work correctly. This fixes the issue and also added a verifier for the SAML JSON configuration so there won't be any nil pointers and #338 can be closed.
=> Handle GET/POST if for SAML routes

admin/static/js/functions.js, admin/templates/carves.html, admin/templates/node.html, admin/templates/queries-logs.html, admin/templates/queries.html, admin/templates/saved.html, admin/templates/table.html
Since AJAX requests must follow 302s transparently, is not possible to catch when a request to a data JSON endpoint redirects to something else (login page), so it needs changes to the server response. Also tried to use the `fetch` method in JavaScript but it was not working correctly and code was too messy. So I just output the error in the console and #138 can be closed as not possible.
=> Show AJAX error in the browser console

api/handlers/environments.go, api/main.go, cli/api-environment.go, cli/tag.go, environments/environments.go
* Adding new path for `osctrl-api` to return a map with all environments by ID, with the name and the UUID
* Utilize the new path with `osctrl-cli` to decorate tags with environment name
=> Decorating tags with environment name via `osctrl-api`

cmd/cli/main.go
The aliases for the `osctrl-cli` command `node-actions` were conflicting and the dev environment for docker and using `provision.sh` was not enrolling nodes.
=> Remove alias in `node-actions` for `osctrl-cli` to avoid conflict

pkg/nodes/utils.go, pkg/nodes/utils_test.go
Adding tests to the utility function `IsActive` for nodes and small fix to compare times in absolute values.
=> Fix to `IsActive` utility function in nodes package

cmd/admin/main.go, cmd/api/main.go, cmd/cli/main.go, cmd/tls/main.go, pkg/nodes/nodes.go, pkg/queries/queries_test.go
Adding cache client to nodes manager so data can be consumed from the cache (Redis).
=> Adding cache client to nodes manager

pkg/nodes/nodes.go
Follow up change for https://github.com/jmpsec/osctrl/pull/609 to assign the cache client when initializing the nodes manager.
=> Assign the cache client when initializing the nodes manager

cmd/admin/templates/node.html, osctrl-api.yaml
With the changes landed in #607 some of the node columns were removed and a new one was added to keep when the node was last seen. This PR fixes the HTML template for `osctrl-admin` to prevent accessing the removed fields.
Also updated the OpenAPI yaml.
=> Use the `last_seen` field in the `node.html` template

pkg/nodes/cache.go, pkg/nodes/utils.go, pkg/nodes/utils_test.go
Ability to cache nodes and retrieve them from cache. Default expiration is 1 hour
=> Caching nodes and retrieving them

cmd/tls/handlers/metrics.go, cmd/tls/handlers/post.go, cmd/tls/handlers/writers.go
Introduce metrics to track the duration of log processing, distributed query processing, and batch flushing operations. 
It helps us to measure the time spent on the background tasks.
=> Add metrics for log processing and batch flush durations

cmd/tls/main.go, cmd/tls/settings.go, pkg/config/flags.go, pkg/logging/logging.go
Fix for `osctrl-tls` after the flags refactor into its own `config` pkg in #619 
With this PR the docker dev environment is operational again.
=> Fix for `osctrl-tls` after refactoring flags and configuration

cmd/api/auth.go, cmd/api/handlers/handlers.go, cmd/api/main.go, cmd/api/settings.go, pkg/config/flags.go, pkg/config/types.go, pkg/settings/settings.go
Complete the refactor in `osctrl-api` to utilize the flags from the new config pkg. It follows up the work in #622 #625 and #627
=> Using new flags from config pkg in `osctrl-api`

pkg/queries/queries.go
Implement batch creation of node queries to handle more than 10,000 nodes efficiently.
It's a quick fix and I think it's a good idea to applied the batchsize as a global configuration for DB cofig.
It can be done by:
```go
db, err := gorm.Open(postgres.Open(dsn), &gorm.Config{
CreateBatchSize: 1000, 
})
```
=> Fix error when creating node queries for large datasets

Makefile
The target `make install_admin` was not using the correct directory under `cmd`
=> Using correct directory for `make install_admin` target

cmd/admin/handlers/handlers.go, cmd/admin/main.go, cmd/api/handlers/handlers.go, cmd/api/main.go, cmd/cli/main.go, cmd/tls/handlers/handlers.go, cmd/tls/handlers/post.go, cmd/tls/main.go, pkg/cache/in-memory.go, pkg/cache/in-memory_test.go, pkg/cache/metrics.go, pkg/environments/env-cache.go, pkg/environments/environments.go, pkg/environments/flags.go, pkg/environments/osqueryconf.go
This PR introduces an in-memory cache to store parameters that rarely change, reducing the number of requests to the backend database. However, it should only be used for bounded values—such as the environment and node key—because the cache is currently unbounded and may grow indefinitely, potentially leading to OOMKilled errors.
At this point, the cache has been added for the `environment` value only.
=> Add inmemory cache for env

.github/workflows/build_and_test_main_merge.yml
Potential fix for [https://github.com/jmpsec/osctrl/security/code-scanning/19](https://github.com/jmpsec/osctrl/security/code-scanning/19)
To fix the issue, we will add a `permissions` block to the workflow. At the root level, we will set the default permissions to `contents: read`, which is sufficient for most CI workflows. For jobs that require additional permissions, such as `push_docker_images`, we will define job-specific permissions to grant only the necessary access.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Potential fix for code scanning alert no. 19: Workflow does not contain permissions

cmd/api/handlers/nodes.go, cmd/api/handlers/utils.go, cmd/cli/api-carve.go, cmd/cli/api-environment.go, cmd/cli/api-login.go, cmd/cli/api-node.go, cmd/cli/api-query.go, cmd/cli/api-tag.go, cmd/cli/api-user.go, cmd/cli/main.go, cmd/cli/node.go, osctrl-api.yaml, pkg/types/types.go
* Adding support in `osctrl-cli` to look up nodes via `osctrl-api`, merged in #657 
* Better output when issuing the `lookup` command
=> Adding support to `osctrl-cli` to look up nodes via `osctrl-api`

pkg/logging/db.go, pkg/logging/elastic.go, pkg/logging/graylog.go, pkg/logging/logstash.go, pkg/logging/splunk.go
Avoid using `strings.NewReader` when `bytes.NewReader` can be used and avoid unnecessary allocation.
=> Refactor `strings.NewReader` into bytes to avoid allocations

cmd/admin/auth.go, cmd/admin/handlers/post.go, cmd/admin/handlers/templates.go, cmd/admin/handlers/types-requests.go, cmd/admin/handlers/types-templates.go, cmd/admin/main.go, cmd/admin/saml.go, cmd/admin/settings.go, cmd/admin/static/js/users.js, cmd/admin/templates/users.html, cmd/cli/main.go, cmd/cli/user.go, pkg/users/permissions_test.go, pkg/users/users.go, pkg/users/users_test.go
- Adding service users to `osctrl-admin` and `osctrl-api`
- Support to add service users using `osctrl-cli`
- Fixed capitalization errors highlighted by `go staticcheck`
- Fixes in unit tests
=> Adding service users

Makefile
Adding `deps-update` to the `Makefile` to keep dependencies up to date with the command `make deps-update`.
=> Adding `deps-update` in Makefile

.github/actions/tagged_release/docker/codesign/action.yml
The parameters for `cosign` command had an incorrect format due to multiple tags.
=> Fix for cosign format due to multiple tags

.github/actions/tagged_release/github/action.yml, .github/workflows/create_tagged_releases.yml
When tagging a release, the job `create_release` was failing due to the push to the `main` branch, and DEB packages being missing.
=> Fix for create_release GHA when tagged

.goreleaser.yml, Makefile, cmd/tls/main.go, cmd/tls/settings.go
Fix for `osctrl-tls` to print out the version and exit when issuing the `-v`, `--version` flag. Also adding metadata to build.
=> Fix for `--version` in `osctrl-tls`

.goreleaser.yml, Makefile, cmd/api/main.go, cmd/cli/main.go
Fix for `osctrl-api` and `osctrl-cli` to print out the version and exit when issuing the `-v`, `--version` flag. Also adding metadata to build.
=> Fix for `--version` in `osctrl-api` and `osctrl-cli`

cmd/cli/main.go
Fix for issue #680 that was causing the ability to tag nodes in `osctrl-cli` to fail. Now it should be fixed:
```
./osctrl-cli -d node tag -u "node-uuid" -e dev -n "new-tag"
✅ node was tagged successfully
```
=> Fix for issue #680 to tag nodes

cmd/api/handlers/nodes.go, cmd/api/main.go, cmd/cli/api-node.go, cmd/cli/node.go, osctrl-api.yaml, pkg/tags/tags.go, pkg/types/types.go
Tagging nodes using `osctrl-cli`, without direct access to the database, it uses the `osctrl-api` component. This code adds the ability to tag nodes in `osctrl-api`.
=> Tagging node using `osctrl-api`

Makefile, docker-compose-dev.yml
Adding two more osquery nodes to the docker dev environment
=> 3 osquery nodes in docker dev environment

pkg/nodes/nodes.go, pkg/nodes/utils.go, pkg/nodes/utils_test.go
Some cleanup for platform stats, no longer needed. Fix for unit tests and node tables were wrongly reporting active nodes as inactive.
=> Fix for active nodes being displayed as inactive

cmd/admin/main.go, cmd/admin/static/css/custom.css, pkg/config/flags.go, pkg/config/types.go
Implementation of #660 
Added two new parameters to `osctrl-admin` to customize the background and branding images.
=> Customization of background and branding images
